DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS news_tags;
DROP TABLE IF EXISTS news;
DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

CREATE TABLE IF NOT EXISTS authors(
	id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	name VARCHAR(15) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS news(
	id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	title VARCHAR(30) UNIQUE NOT NULL,
	content VARCHAR(255),
	authors_id BIGINT,
	FOREIGN KEY(authors_id)
		REFERENCES authors(id),
	created VARCHAR(30),
	modified VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS comments(
	id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	content VARCHAR(255),
	news_id BIGINT,
	FOREIGN KEY (news_id)
		REFERENCES news (id),
	created VARCHAR(30),
	modified VARCHAR(30)
);

CREATE TABLE if NOT EXISTS tags(
	id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	name VARCHAR(15) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS news_tags(
	id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	news_id BIGINT,
	FOREIGN KEY (news_id)
		REFERENCES news (id),
	tags_id BIGINT,
	FOREIGN KEY (tags_id)
	    REFERENCES tags (id)
);

CREATE TABLE IF NOT EXISTS roles(
    id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS users(
    id bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
    email VARCHAR(255),
    login VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    roles_id BIGINT,
    FOREIGN KEY (roles_id)
        REFERENCES roles (id)
);