CREATE DATABASE IF NOT EXISTS news_management;

DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS news_tags;
DROP TABLE IF EXISTS news;
DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS tags;

CREATE TABLE IF NOT EXISTS authors(
	id BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY ,
	name VARCHAR(15) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS news(
	id BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
	title VARCHAR(30) UNIQUE NOT NULL,
	content VARCHAR(255),
	authors_id BIGINT,
	FOREIGN KEY(authors_id)
		REFERENCES authors(id),
	created VARCHAR(30),
	modified VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS comments(
	id BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
	content VARCHAR(255),
	news_id BIGINT,
	FOREIGN KEY (news_id)
		REFERENCES news (id),
	created VARCHAR(30),
	modified VARCHAR(30)
);

CREATE TABLE if NOT EXISTS tags(
	id BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(15) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS news_tags(
	id BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
	news_id BIGINT,
	FOREIGN KEY (news_id)
		REFERENCES news (id),
	tags_id BIGINT,
	FOREIGN KEY (tags_id)
	REFERENCES tags (id)
);

GRANT ALL PRIVILEGES ON DATABASE "news_management" to root;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "root";

INSERT INTO authors(name)
VALUES ('Alex'), ('Max'), ('Jon'), ('Tony'), ('Tom'), ('Alisa');

